name: serene
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  animations: ^1.0.0+5
  flutter_staggered_grid_view: ^0.3.0
  flutter_bloc: ^3.2.0
  equatable: ^1.1.1
  audioplayers: ^0.15.1
  intl: ^0.16.1
  flare_flutter: ^1.8.3
  flutter_launcher_icons: "^0.8.0"
  # mopub_flutter: ^1.2.2+1
  # google_mobile_ads: ^0.12.1+1
  firebase_admob: ^0.5.2
  get_storage: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"  

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/city/
    - assets/images/meditation/
    - assets/images/forest/
    - assets/images/rain/
    - assets/audios/
    - assets/animation/
  fonts:
    - family: Caveat
      fonts:
        - asset: fonts/Caveat-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700

